CREATE TABLE team_leagues(
	url bigint NOT NULL,
	league_name VARCHAR(100),
	PRIMARY KEY(url)
);

CREATE TABLE players(
	id serial,
	sofifa_id bigint NOT NULL,
	player_url varchar(250),
	short_name varchar(50),
	long_name varchar(100),
	age int,
	dob date,
	height_cm int,
	weight_kg int,
	nationality varchar(50),
	club varchar(100),
	overall int,
	potential int,
	value_eur int,
	wage_eur int,
	player_positions varchar(50),
	preferred_foot varchar(15),
	international_reputation varchar(50),
	weak_foot int,
	skill_moves int,
	work_rate varchar(50),
	body_type varchar(20),
	real_face boolean,
	release_clause_eur varchar(50),
	player_tags varchar(200),
	team_position varchar(10),
	team_jersey_number int,
	loaned_from varchar(50),
	joined date,
	contract_valid_until int ,
	nation_position varchar(10),
	nation_jersey_number int,
	pace int,
	shooting int,
	passing int,
	dribbling int,
	defending int,
	physic int,
	gk_diving int,
	gk_handling int,
	gk_kicking int,
	gk_reflexes int,
	gk_speed int,
	gk_positioning int,
	player_traits varchar(350),
	attacking_crossing varchar(10),
	attacking_finishing varchar(10),
	attacking_heading_accuracy varchar(10),
	attacking_short_passing varchar(10),
	attacking_volleys varchar(10),
	skill_dribbling varchar(10),
	skill_curve varchar(10),
	skill_fk_accuracy varchar(10),
	skill_long_passing varchar(10),
	skill_ball_control varchar(10),
	movement_acceleration varchar(10),
	movement_sprint_speed varchar(10),
	movement_agility varchar(10),
	movement_reactions varchar(10),
	movement_balance varchar(10),
	power_shot_power varchar(10),
	power_jumping varchar(10),
	power_stamina varchar(10),
	power_strength varchar(10),
	power_long_shots varchar(10),
	mentality_aggression varchar(10),
	mentality_interceptions varchar(10),
	mentality_positioning varchar(10),
	mentality_vision varchar(10),
	mentality_penalties varchar(10),
	mentality_composure varchar(10),
	defending_marking varchar(10),
	defending_standing_tackle varchar(10),
	defending_sliding_tackle varchar(10),
	goalkeeping_diving varchar(10),
	goalkeeping_handling varchar(10),
	goalkeeping_kicking varchar(10),
	goalkeeping_positioning varchar(10),
	goalkeeping_reflexes varchar(10),
	ls varchar(10),
	st varchar(10),
	rs varchar(10),
	lw varchar(10),
	lf varchar(10),
	cf varchar(10),
	rf varchar(10),
	rw varchar(10),
	lam varchar(10),
	cam varchar(10),
	ram varchar(10),
	lm varchar(10),
	lcm varchar(10),
	cm varchar(10),
	rcm varchar(10),
	rm varchar(10),
	lwb varchar(10),
	ldm varchar(10),
	cdm varchar(10),
	rdm varchar(10),
	rwb varchar(10),
	lb varchar(10),
	lcb varchar(10),
	cb varchar(10),
	rcb varchar(10),
	rb varchar(10),
	PRIMARY KEY(id)
);


SELECT count(*) from players; 